name: Custom Workflow

on:
  push:
    branches: [develop] 

jobs:
  custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 

      - name: Setup Node.js 18
        uses: actions/setup-node@v3 
        with:
          node-version: '18'

      - name: Install and Test
        run: |
          cd sample-app
          npm install
          npm test

      - name: Access secret safely
        run: echo "My secret code is ${{ secrets.TEST_SECRET }}"